services:
  postgres:
    container_name: 3d-print-helper-postgres
    image: postgres:16
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: print-helper
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
